from six import print_ as p
import unittest
from imap_detach.imap_client import walker

BODY=([([(b'TEXT',
     b'PLAIN',
     (b'CHARSET', b'ISO-8859-1', b'FORMAT', b'flowed'),
     None,
     None,
     b'7BIT',
     1145,
     22,
     None,
     None,
     None,
     None),
    ([(b'TEXT',
       b'HTML',
       (b'CHARSET', b'ISO-8859-1'),
       None,
       None,
       b'7BIT',
       7447,
       180,
       None,
       None,
       None,
       None),
      (b'IMAGE',
       b'GIF',
       (b'NAME', b'haedjgag.gif'),
       b'<part1.01050901.01000603@example.com>',
       None,
       b'BASE64',
       18158,
       None,
       (b'INLINE', (b'FILENAME', b'haedjgag.gif')),
       None,
       None),
      (b'IMAGE',
       b'PNG',
       (b'NAME', b'cgjhfabb.png'),
       b'<part5.09080607.06070109@example.com>',
       None,
       b'BASE64',
       1808,
       None,
       (b'INLINE', (b'FILENAME', b'cgjhfabb.png')),
       None,
       None),
      (b'IMAGE',
       b'JPG',
       (b'NAME', b'ijcbgecj.'),
       b'<part6.05040701.09070509@example.com>',
       None,
       b'BASE64',
       12020,
       None,
       (b'INLINE', (b'FILENAME', b'ijcbgecj.')),
       None,
       None),
      (b'IMAGE',
       b'JPG',
       (b'NAME', b'icfhaegi.'),
       b'<part8.00030901.09000500@example.com>',
       None,
       b'BASE64',
       12542,
       None,
       (b'INLINE', (b'FILENAME', b'icfhaegi.')),
       None,
       None),
      (b'IMAGE',
       b'JPG',
       (b'NAME', b'jdhhjfih.'),
       b'<part10.06070505.03070702@example.com>',
       None,
       b'BASE64',
       15004,
       None,
       (b'INLINE', (b'FILENAME', b'jdhhjfih.')),
       None,
       None),
      (b'IMAGE',
       b'JPG',
       (b'NAME', b'biiddjee.'),
       b'<part12.09060909.01040008@example.com>',
       None,
       b'BASE64',
       12846,
       None,
       (b'INLINE', (b'FILENAME', b'biiddjee.')),
       None,
       None),
      (b'IMAGE',
       b'JPG',
       (b'NAME', b'hidffibg.'),
       b'<part14.03000507.06070001@example.com>',
       None,
       b'BASE64',
       9902,
       None,
       (b'INLINE', (b'FILENAME', b'hidffibg.')),
       None,
       None)],
     b'RELATED',
     (b'BOUNDARY', b'------------090804090502080900080501'),
     None,
     None,
     None)],
   b'ALTERNATIVE',
   (b'BOUNDARY', b'------------020403030206060806080603'),
   None,
   None,
   None),
  (b'TEXT',
   b'CSV',
   (b'NAME', b'PDF_checker.csv'),
   None,
   None,
   b'8BIT',
   7517136,
   39211,
   None,
   (b'ATTACHMENT', (b'FILENAME', b'PDF_checker.csv')),
   None,
   None)],
 b'MIXED',
 (b'BOUNDARY', b'------------010808060905080909070704'),
 None,
 None,
 None)

class Test(unittest.TestCase):

    def test(self):
        sec_2=False
        for info in walker(BODY):
            p(info)
            if info.section =='2':
                self.assertEqual(info.type, 'text')
                self.assertEqual(info.sub_type, 'csv')
                sec_2=True
        self.assertTrue(sec_2)


if __name__ == "__main__":
    #import sys;sys.argv = ['', 'Test.testName']
    unittest.main()